name: CICD-workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: build front end
      run: cd frontend-admin && npm run build
      
    - name: delete back end build file, copy front end build, paste back end build
      run: rm -r backend/public/build && cp -r frontend-admin/build backend/public

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        project_id: quizlet-01
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
    - name: Authenticate Google Cloud
      run: |-
         echo '${{ secrets.SERVICE_ACCOUNT_KEY }}' | gcloud auth activate-service-account quizlet-01@appspot.gserviceaccount.com \
         --key-file=- --project=quizlet-01
        
    - name: Deploy to GCloud
      run: cd backend && gcloud app deploy
