name: CICD-workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        project_id: quizlet-01
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
    - name: Authenticate Google Cloud
      run: |-
        gcloud auth activate-service-account --quiet
        
    - name: Deploy to GCloud
      run: gcloud app deploy
